# before_commands:
#     - npm install

tools:
    js_hint:
        enabled: true
        filter:
            paths: [ 'src/' ]

#    custom_commands:
#        -
#            scope: project
#            command: grunt
