language: node_js

node_js:
  - 0.10

install:
- npm -d install
- npm install -g gulp

script:
- gulp lint
- gulp test

after_script:
- cat ./dist/coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js
